metadata:
  name: mautic-subscribe-promote
  namespace: de0974-tools
spec:
  templates:
    - name: main
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: clone
            template: clone
            arguments: {}
        - - name: get-keycloak-sa-secret
            template: get-keycloak-sa-secret
            arguments: {}
        - - name: create-keycloak-client
            template: create-keycloak-client
            arguments: {}
        - - name: re-tag-image 
            template: re-tag-image
            arguments: {}
        - - name: deploy-mautic-subscription-app
            template: deploy-mautic-subscription-app
            arguments: {}    


    - name: clone
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/alpine/git:v2.26.2'
        args:
          - clone
          - '--depth'
          - '1'
          - '--branch'
          - '{{workflow.parameters.SOURCE_REPOSITORY_REF}}'
          - '--single-branch'
          - '{{workflow.parameters.SOURCE_REPOSITORY_URL}}'
        workingDir: /mnt/vol
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: get-keycloak-sa-secret
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args:
          - >-
            oc delete all,configmap -l app={{workflow.parameters.APP_NAME}} -n {{workflow.parameters.TARGET_NAMESPACE}};
            oc get secret sso-service-account -o jsonpath={'.data.SSO_SA_CLIENT_ID'} -n de0974-tools | base64 --decode > SSO_SA_CLIENT_ID.txt;
            oc get secret sso-service-account -o jsonpath={'.data.SSO_SA_PASSWORD'} -n de0974-tools | base64 --decode > SSO_SA_PASSWORD.txt

        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: create-keycloak-client
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/giantswarm/tiny-tools'
        command:
          - sh
          - '-c'
        args:
          - >-
            NAME={{workflow.parameters.APP_NAME}} TARGET_NAMESPACE={{workflow.parameters.TARGET_NAMESPACE}} KEYCLOAK_URL={{workflow.parameters.KEYCLOAK_URL}} 
            KEYCLOAK_CLIENT_ID=`cat SSO_SA_CLIENT_ID.txt` KEYCLOAK_CLIENT_SECRET=`cat SSO_SA_PASSWORD.txt` REALM_NAME={{workflow.parameters.SSO_REALM}} 
            ./keycloak-client-creation/kc-create-client.sh https://{{workflow.parameters.APP_NAME}}-{{workflow.parameters.IMAGE_TAG}}-{{workflow.parameters.TARGET_NAMESPACE}}.{{workflow.parameters.HOST_ADDRESS}}/*;
            
            jq --arg SSO_CLIENT_ID "$SSO_CLIENT_ID" '.clientId = "{{workflow.parameters.APP_NAME}}-{{workflow.parameters.IMAGE_TAG}}"' "public/config/sso_example.json" > public/config/sso.json;

        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol
    - name: re-tag-image
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args:
          - >-
            oc tag {{workflow.parameters.TOOLS_NAMESPACE}}/{{workflow.parameters.APP_NAME}}:{{workflow.parameters.PR}}
            {{workflow.parameters.TARGET_NAMESPACE}}/{{workflow.parameters.APP_NAME}}:{{workflow.parameters.IMAGE_TAG}} 
        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: deploy-mautic-subscription-app
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args: 
          - >-
            oc delete configmap mautic-config;
            oc process -f openshift/mautic.subscribe.dc.yaml 
            -p APP_NAME={{workflow.parameters.APP_NAME}}
            -p IMAGE_TAG={{workflow.parameters.IMAGE_TAG}} 
            -p TARGET_NAMESPACE={{workflow.parameters.TARGET_NAMESPACE}}
            -p SUBSCRIBE_FORM={{workflow.parameters.SUBSCRIBE_FORM}}
            -p UNSUBSCRIBE_FORM={{workflow.parameters.UNSUBSCRIBE_FORM}}
            -p SUBSCRIBE_URL={{workflow.parameters.SUBSCRIBE_URL}}
            -p UNSUBSCRIBE_URL={{workflow.parameters.UNSUBSCRIBE_URL}}
            -p KEYCLOAK_URL={{workflow.parameters.KEYCLOAK_URL}}
            -p SSO_REALM={{workflow.parameters.SSO_REALM}}
            -p SSO_CLIENT_ID={{workflow.parameters.APP_NAME}}-{{workflow.parameters.IMAGE_TAG}}
            -p IMAGE_REGISTRY={{workflow.parameters.IMAGE_REGISTRY}}
            -n {{workflow.parameters.TARGET_NAMESPACE}}
            | oc apply -f - -n {{workflow.parameters.TARGET_NAMESPACE}}
        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

  entrypoint: main
  arguments: {}
  serviceAccountName: workflow-creator
  volumeClaimTemplates:
    - metadata:
        name: work
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
        storageClassName: netapp-file-standard
      status: {}
  imagePullSecrets:
    - name: dockerhub-secret-mautic

