metadata:
  name: mautic-subscribe-promote
  namespace: de0974-tools
spec:
  templates:
    - name: main
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: clone
            template: clone
            arguments: {}
        - - name: re-tag-image 
            template: re-tag-image
            arguments: {}
        - - name: deploy-mautic
            template: deploy-mautic
            arguments: {}    


    - name: clone
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/alpine/git:v2.26.2'
        args:
          - clone
          - '--depth'
          - '1'
          - '--branch'
          - '{{workflow.parameters.BRANCH}}'
          - '--single-branch'
          - '{{workflow.parameters.REPO}}'
        workingDir: /mnt/vol
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: re-tag-image
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args:
          - >-
            echo "tagging image to {{workflow.parameters.TARGET_NAMESPACE}}";
            oc tag {{workflow.parameters.TOOLS_NAMESPACE}}/{{workflow.parameters.NAME}}:{{workflow.parameters.IMAGE_TAG}}
            {{workflow.parameters.TARGET_NAMESPACE}}/{{workflow.parameters.NAME}}:{{workflow.parameters.IMAGE_TAG}} 
        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: deploy-mautic
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args: 
          - >-
            oc delete configmap mautic-form-config;
            oc delete configmap mautic-sso-config;
            oc create configmap mautic-form-config -n {{workflow.parameters.TARGET_NAMESPACE}} --from-file=public/config/form.json;
            oc create configmap mautic-sso-config -n {{workflow.parameters.TARGET_NAMESPACE}} --from-file=public/config/sso.json;
            oc process -f openshift/mautic.subscribe.dc.yaml 
            -p SUFFIX={{workflow.parameters.SUFFIX}} 
            -p IMAGE_NAME={{workflow.parameters.NAME}} 
            -p IMAGE_TAG={{workflow.parameters.IMAGE_TAG}} 
            -p TARGET_NAMESPACE={{workflow.parameters.TARGET_NAMESPACE}}
            -n {{workflow.parameters.TARGET_NAMESPACE}}
            | oc apply -f - -n {{workflow.parameters.TARGET_NAMESPACE}}
        workingDir: /mnt/vol/Mautic-Subscription-App
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

  entrypoint: main
  arguments: {}
  serviceAccountName: workflow-creator
  volumeClaimTemplates:
    - metadata:
        name: work
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
        storageClassName: netapp-file-standard
      status: {}
  imagePullSecrets:
    - name: dockerhub-secret-mautic

