apiVersion: v1
kind: Template
metadata:
  name: argo-template
  annotations:
    description: "Grant workflow-creator service account edit access to the dev namespace"

labels:
  app: argo-workflow

objects:

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: edit-dev
    namespace: ${DEV_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: edit
  subjects:
  - kind: ServiceAccount
    name: workflow-creator
    namespace: ${TOOLS_NAMESPACE}

parameters:
- description: Tools Namespace
  displayName: Tools Namespace
  name: TOOLS_NAMESPACE
  required: true
- description: dev Namespace
  displayName: dev Namespace
  name: DEV_NAMESPACE
  required: true