kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    stringData:
      SSO_SA_CLIENT_ID: ${SSO_CLIENT_ID}
      SSO_SA_PASSWORD: ${SSO_SECRET}
    kind: Secret
    metadata:
      creationTimestamp: null
      name: sso-service-account
      namespace: de0974-tools
parameters:
- description: SSO client id
  displayName: SSO_CLIENT_ID
  name: SSO_CLIENT_ID
  required: true
- description: SSO secret
  displayName: SSO_SECRET
  name: SSO_SECRET
  required: true
